/*

This is a JavaScript file you can edit to add custom markers to the map.
uNmINeD does not overwrite this file during map generation.

Steps:

    1. Edit this file using Notepad or a code editor (do not use document editors like Microsoft Word)
    2. Change the line "isEnabled: false," to "isEnabled: true," to display the markers
    3. Change or remove the example markers
    4. Add your own markers

Marker format:

    {
        x: X coordinate of the marker (in Minecraft block units),
        z: Z coordinate of the marker (in Minecraft block units),
        image: marker image URL to display (in quotes),
        imageScale: scale of the image (e.g. 1 = display full size, 0.5 = display half size),
        imageAnchor: [0.5, 1] means the tip of the pin is at the center-bottom of the image (see OpenLayers documentation for more info),
        text: marker text do display (in quotes),
        textColor: text color in HTML/CSS format (in quotes),
        offsetX: horizontal pixel offset of the text,
        offsetY: vertical pixel offset of the text,
        font: text font in HTML/CSS format (in quotes),
    },

Things to keep in mind:

* There are opening and closing brackets for each marker "{" and "}"
* Property names are case sensitive (i.e. "textColor" is okay, "TextColor" is not)
* There is a comma (",") at the end of each line except the opening brackets ("{")

You can use https://mapmarker.io/editor to generate custom pin images.
Use the imageScale property if the pin image is too large.

*/
line1Color = "#253B94";
line2Color = "#3AB449";

cultureColor = "#BD91BD";
heritageColor = "#A2895F";
hospitalColor = "#FBCECE";
hotelColor = "#D6C8FF";
houseColor = "#D9BC98";
natureColor = "#C5FFAC";
restaurantColor = "#FFC36F";
sportColor = "#CDFDFD";
universityColor = "#8CCFF9";

UnminedCustomMarkers = {

    isEnabled: true,

    markers: [

        /*
        // Example 1: Simple marker
        {
            x: -200,
            z: -200,
            image: "pinImages/custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
        },

        // Example 2: Marker with text
        {
            x: 0,
            z: 0,
            image: "pinImages/custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Marker with text",
            textColor: "red", 
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Calibri,sans serif",
        },

        // Example 3: Text only
        {
            x: 200,
            z: 200,
            text: "Text only", 
            textColor: "yellow", 
            offsetX: 0,
            offsetY: 0, 
            font: "bold 50px Calibri,sans serif",
        },
        */
        // add your markers here
        //ㄱ
        {
            x: 868,
            z: -8,
            image: "pinImages/heritage.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "강동문",
            textColor: heritageColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 269,
            z: -143,
            image: "pinImages/university.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "건축대학",
            textColor: universityColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -318,
            z: -264,
            image: "pinImages/normal.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "건축부",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 192,
            z: -57,
            text: "건축실습관",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,
            offsetX: 0,
            offsetY: 0,
            font: "bold 12px Calibri,sans serif",
        },
        {
            x: -1062,
            z: 0,
            image: "pinImages/line2.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "경용대역",
            textColor: "white",
            textStrokeColor: line2Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -953,
            z: 87,
            image: "pinImages/university.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "경용대학교",
            textColor: universityColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 302,
            z: 465,
            image: "pinImages/normal.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "고등법원",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 938,
            z: -438,
            image: "pinImages/university.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "공군사관학교",
            textColor: universityColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -9,
            z: -106,
            text: "공학관",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,
            offsetX: 0,
            offsetY: 0,
            font: "bold 12px Calibri,sans serif",
        },
        {
            x: -21,
            z: -154,
            text: "과학연구센터",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,
            offsetX: 0,
            offsetY: 0,
            font: "bold 12px Calibri,sans serif",
        },
        {
            x: -647,
            z: 390,
            image: "pinImages/line1.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "광장역",
            textColor: "white",
            textStrokeColor: line1Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -358,
            z: 281,
            image: "pinImages/line1.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "광화문역",
            textColor: "white",
            textStrokeColor: line1Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 1126,
            z: 1046,
            image: "pinImages/house.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "구룡마을",
            textColor: houseColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -237,
            z: -372,
            image: "pinImages/theater.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "국립극장",
            textColor: cultureColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -573,
            z: -372,
            image: "pinImages/museum.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "국립박물관",
            textColor: cultureColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -533,
            z: -257,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "근대자동차",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 1279,
            z: 1171,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "근대자동차공장",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -254,
            z: -205,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "금융공유오피스",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -750,
            z: 108,
            image: "pinImages/restaurant.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "김밥제국",
            textColor: restaurantColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },

        //ㄴ
        {
            x: 452,
            z: 895,
            image: "pinImages/line2.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "남해역",
            textColor: "white",
            textStrokeColor: line2Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 66,
            z: -158,
            text: "노천극장",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,
            offsetX: 0,
            offsetY: 0,
            font: "bold 12px Calibri,sans serif",
        },

        //ㄷ
        {
            x: -252,
            z: -170,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "달태제과",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 452,
            z: 543,
            image: "pinImages/line2.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "대법원역",
            textColor: "white",
            textStrokeColor: line2Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -102,
            z: -321,
            text: "대운동장",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,
            offsetX: 0,
            offsetY: 0,
            font: "bold 12px Calibri,sans serif",
        },
        {
            x: 150,
            z: 30,
            image: "pinImages/restaurant.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "던킹도너츠",
            textColor: restaurantColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -373,
            z: 91,
            image: "pinImages/heritage.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "도민궁",
            textColor: heritageColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 1279,
            z: 1249,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "도요새공장",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -393,
            z: -50,
            image: "pinImages/line1.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "돈화문역",
            textColor: "white",
            textStrokeColor: line1Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 653,
            z: -8,
            image: "pinImages/heritage.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "동대문",
            textColor: heritageColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 714,
            z: -7,
            image: "pinImages/line1.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "동대문역",
            textColor: "white",
            textStrokeColor: line1Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 454,
            z: -419,
            image: "pinImages/line2.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "동촌역",
            textColor: "white",
            textStrokeColor: line2Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },

        //ㄹ

        //ㅁ
        {
            x: -467,
            z: -264,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "마크타임즈",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 148,
            z: 133,
            image: "pinImages/restaurant.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "명량핫도그",
            textColor: restaurantColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 196,
            z: -117,
            image: "pinImages/heritage.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "명륜당",
            textColor: heritageColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -1062,
            z: -306,
            image: "pinImages/line2.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "민텍스역",
            textColor: "white",
            textStrokeColor: line2Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },

        //ㅂ
        {
            x: -615,
            z: 143,
            image: "pinImages/theater.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "밸로보그극장",
            textColor: cultureColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 167,
            z: 4,
            image: "pinImages/fastfood.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "버거황",
            textColor: restaurantColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -596,
            z: 321,
            image: "pinImages/park.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "버섯석탑공원",
            textColor: natureColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 85,
            z: 17,
            image: "pinImages/heritage.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "보신각",
            textColor: heritageColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -654,
            z: -141,
            image: "pinImages/park.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "북궁공원",
            textColor: natureColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -320,
            z: -134,
            image: "pinImages/goverment.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "북해동주민센터",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 967,
            z: 321,
            image: "pinImages/mountain.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "빙산",
            textColor: natureColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },

        //ㅅ
        {
            x: -1062,
            z: 389,
            image: "pinImages/line2.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "서대문역",
            textColor: "white",
            textStrokeColor: line2Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 1193,
            z: -8,
            image: "pinImages/heritage.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "서래타워",
            textColor: heritageColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -711,
            z: 436,
            image: "pinImages/goverment.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "서문동주민센터",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -1206,
            z: 288,
            image: "pinImages/mountain.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "서악산",
            textColor: natureColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -591,
            z: 1197,
            image: "pinImages/line2.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "서운대역",
            textColor: "white",
            textStrokeColor: line2Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 346,
            z: 20,
            image: "pinImages/goverment.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "성내구청",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: 71,
            z: 464,
            image: "pinImages/normal.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "성내중앙지방검찰청",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 1271,
            z: 301,
            image: "pinImages/normal.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "성동경찰청",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 1769,
            z: 1114,
            image: "pinImages/goverment.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "성동구청",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: 1987,
            z: 1181,
            image: "pinImages/stadium.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "성동성경기장",
            textColor: sportColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 1119,
            z: 941,
            image: "pinImages/house.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "성동시민아파트1단지",
            textColor: houseColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 1196,
            z: -233,
            image: "pinImages/heritage.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "소환신전",
            textColor: heritageColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 249,
            z: 17,
            image: "pinImages/heritage.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "수덕궁",
            textColor: heritageColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 151,
            z: -29,
            image: "pinImages/line1.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "수덕궁역",
            textColor: "white",
            textStrokeColor: line1Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 117,
            z: 534,
            image: "pinImages/normal.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "수민고등검찰청",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 142,
            z: -496,
            image: "pinImages/line2.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "수민대기숙사역",
            textColor: "white",
            textStrokeColor: line2Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -65,
            z: -37,
            image: "pinImages/line1.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "수민대역",
            textColor: "white",
            textStrokeColor: line1Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 281,
            z: -247,
            image: "pinImages/university.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "수민대학교",
            textColor: universityColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -163,
            z: -97,
            image: "pinImages/hospital.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "수민대학교병원",
            textColor: hospitalColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -330,
            z: -190,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "수민은행",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 1249,
            z: 1101,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "수민전력공사",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 1920,
            z: 971,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "수민주택공사",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -485,
            z: -145,
            image: "pinImages/goverment.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "수민특별시청",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: -753,
            z: 63,
            image: "pinImages/cafe.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "스타벅스",
            textColor: restaurantColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 44,
            z: 7,
            image: "pinImages/goverment.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "시작동주민센터",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 452,
            z: -8,
            image: "pinImages/line1.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "시작역",
            textColor: "white",
            textStrokeColor: line1Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 452,
            z: 135,
            image: "pinImages/line2.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "시작역",
            textColor: "white",
            textStrokeColor: line2Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 1193,
            z: 132,
            image: "pinImages/line1.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "신설산역",
            textColor: "white",
            textStrokeColor: line1Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },

        //ㅇ
        {
            x: -92,
            z: -176,
            text: "약학관",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,
            offsetX: 0,
            offsetY: 0,
            font: "bold 12px Calibri,sans serif",
        },
        {
            x: 1195,
            z: 353,
            image: "pinImages/normal.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "우정국",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -108,
            z: -100,
            text: "의학관",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,
            offsetX: 0,
            offsetY: 0,
            font: "bold 12px Calibri,sans serif",
        },
        {
            x: -27,
            z: -207,
            text: "이학관",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,
            offsetX: 0,
            offsetY: 0,
            font: "bold 12px Calibri,sans serif",
        },
        {
            x: -847,
            z: -380,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "은하은행",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },

        //ㅈ
        {
            x: -672,
            z: -9,
            image: "pinImages/fastfood.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "조테리아",
            textColor: restaurantColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 1940,
            z: 1367,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "중국은행",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -730,
            z: -258,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "중소기업센터",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 51,
            z: -206,
            image: "pinImages/university.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "중앙도서관",
            textColor: universityColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -391,
            z: -496,
            image: "pinImages/line2.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "중앙역",
            textColor: "white",
            textStrokeColor: line2Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -252,
            z: -257,
            image: "pinImages/house.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "중앙오피스텔",
            textColor: houseColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -956,
            z: 777,
            image: "pinImages/line2.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "지수역",
            textColor: "white",
            textStrokeColor: line2Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -531,
            z: 771,
            text: "지수호",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,
            offsetX: 0,
            offsetY: 0,
            font: "bold 12px Calibri,sans serif",
        },
        {
            x: 1103,
            z: 469,
            image: "pinImages/university.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "진리극지연구소",
            textColor: universityColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 1278,
            z: 456,
            image: "pinImages/university.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "진리지질연구소",
            textColor: universityColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 1452,
            z: 810,
            image: "pinImages/university.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "진리천문연구소",
            textColor: universityColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },

        //ㅊ
        {
            x: -358,
            z: 439,
            image: "pinImages/normal.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "청와당",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 857,
            z: 1087,
            image: "pinImages/port.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "청해항",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 316,
            z: -78,
            image: "pinImages/heritage.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "춘건루",
            textColor: heritageColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },

        //ㅋ
        {
            x: -918,
            z: -376,
            image: "pinImages/hotel.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "콘래드호텔",
            textColor: hotelColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },

        //ㅌ

        //ㅍ
        {
            x: 160,
            z: 223,
            image: "pinImages/bakery.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "파리바게트",
            textColor: restaurantColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },

        //ㅎ
        {
            x: 47,
            z: -311,
            text: "학생회관",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,
            offsetX: 0,
            offsetY: 0,
            font: "bold 12px Calibri,sans serif",
        },
        {
            x: 1794,
            z: 839,
            image: "pinImages/mountain.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "화악산",
            textColor: natureColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -19,
            z: 1197,
            image: "pinImages/line2.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "해만역",
            textColor: "white",
            textStrokeColor: line2Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },

        //ABC
        {
            x: -249,
            z: -116,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "CN건설",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 1271,
            z: 231,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "EES",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 1194,
            z: 268,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "HBC",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 2037,
            z: 1423,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "HSBD",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 1865,
            z: 1037,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "KY건설",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 139,
            z: 359,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "M&M로펌",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -665,
            z: -269,
            image: "pinImages/building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "SM텔레콤",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 1243,
            z: 591,
            image: "pinImages/university.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "STEAM",
            textColor: universityColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },



        // do not delete the following two closing brackets
    ]
}
