/*

This is a JavaScript file you can edit to add custom markers to the map.
uNmINeD does not overwrite this file during map generation.

Steps:

    1. Edit this file using Notepad or a code editor (do not use document editors like Microsoft Word)
    2. Change the line "isEnabled: false," to "isEnabled: true," to display the markers
    3. Change or remove the example markers
    4. Add your own markers

Marker format:

    {
        x: X coordinate of the marker (in Minecraft block units),
        z: Z coordinate of the marker (in Minecraft block units),
        image: marker image URL to display (in quotes),
        imageScale: scale of the image (e.g. 1 = display full size, 0.5 = display half size),
        imageAnchor: [0.5, 1] means the tip of the pin is at the center-bottom of the image (see OpenLayers documentation for more info),
        text: marker text do display (in quotes),
        textColor: text color in HTML/CSS format (in quotes),
        offsetX: horizontal pixel offset of the text,
        offsetY: vertical pixel offset of the text,
        font: text font in HTML/CSS format (in quotes),
    },

Things to keep in mind:

* There are opening and closing brackets for each marker "{" and "}"
* Property names are case sensitive (i.e. "textColor" is okay, "TextColor" is not)
* There is a comma (",") at the end of each line except the opening brackets ("{")

You can use https://mapmarker.io/editor to generate custom pin images.
Use the imageScale property if the pin image is too large.

*/
line1Color = "#253B94";
universityColor = "#8CCFF9";
heritageColor = "#A2895F";
cultureColor = "#BD91BD";

UnminedCustomMarkers = {

    isEnabled: true,

    markers: [

        /*
        // Example 1: Simple marker
        {
            x: -200,
            z: -200,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
        },

        // Example 2: Marker with text
        {
            x: 0,
            z: 0,
            image: "custom.pin.png",
            imageAnchor: [0.5, 1],
            imageScale: 0.5,
            text: "Marker with text",
            textColor: "red", 
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Calibri,sans serif",
        },

        // Example 3: Text only
        {
            x: 200,
            z: 200,
            text: "Text only", 
            textColor: "yellow", 
            offsetX: 0,
            offsetY: 0, 
            font: "bold 50px Calibri,sans serif",
        },
        */
        // add your markers here
        {
            x: 269,
            z: -143,
            image: "university.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "건축대학",
            textColor: universityColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -318,
            z: -264,
            image: "normal.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "건축부",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 192,
            z: -57,
            text: "건축실습관",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,
            offsetX: 0,
            offsetY: 0,
            font: "bold 12px Calibri,sans serif",
        },
        {
            x: -953,
            z: 87,
            image: "university.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "경용대학교",
            textColor: universityColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 938,
            z: -438,
            image: "university.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "공군사관학교",
            textColor: universityColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -9,
            z: -106,
            text: "공학관",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,
            offsetX: 0,
            offsetY: 0,
            font: "bold 12px Calibri,sans serif",
        },
        {
            x: -21,
            z: -154,
            text: "과학연구센터",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,
            offsetX: 0,
            offsetY: 0,
            font: "bold 12px Calibri,sans serif",
        },
        {
            x: -237,
            z: -372,
            image: "theater.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "국립극장",
            textColor: cultureColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -573,
            z: -372,
            image: "museum.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "국립박물관",
            textColor: cultureColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -533,
            z: -257,
            image: "building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "근대자동차",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        //ㄷ
        {
            x: -252,
            z: -170,
            image: "building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "달태제과",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -102,
            z: -321,
            text: "대운동장",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,
            offsetX: 0,
            offsetY: 0,
            font: "bold 12px Calibri,sans serif",
        },
        {
            x: 66,
            z: -158,
            text: "노천극장",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,
            offsetX: 0,
            offsetY: 0,
            font: "bold 12px Calibri,sans serif",
        },
        {
            x: -373,
            z: 91,
            image: "heritage.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "도민궁",
            textColor: heritageColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -393,
            z: -50,
            image: "line1.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "돈화문역",
            textColor: "white",
            textStrokeColor: line1Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 653,
            z: -8,
            image: "heritage.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "동대문",
            textColor: heritageColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 714,
            z: -7,
            image: "line1.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "동대문역",
            textColor: "white",
            textStrokeColor: line1Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 454,
            z: -419,
            image: "line2.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "동촌역",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        //ㅁ
        {
            x: -467,
            z: -264,
            image: "building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "마크타임즈",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 196,
            z: -117,
            image: "heritage.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "명륜당",
            textColor: heritageColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },

        //ㅂ
        {
            x: -615,
            z: 143,
            image: "theater.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "밸로보그극장",
            textColor: cultureColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 85,
            z: 17,
            image: "heritage.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "보신각",
            textColor: heritageColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -320,
            z: -134,
            image: "goverment.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "북해동주민센터",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },

        //ㅅ
        {
            x: -711,
            z: 436,
            image: "goverment.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "서문동주민센터",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 346,
            z: 20,
            image: "goverment.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "성내구청",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: 249,
            z: 17,
            image: "heritage.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "수덕궁",
            textColor: heritageColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 151,
            z: -29,
            image: "line1.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "수덕궁역",
            textColor: "white",
            textStrokeColor: line1Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 142,
            z: -496,
            image: "line2.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "수민대기숙사역",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -65,
            z: -37,
            image: "line1.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "수민대역",
            textColor: "white",
            textStrokeColor: line1Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 281,
            z: -247,
            image: "university.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "수민대학교",
            textColor: universityColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -330,
            z: -190,
            image: "building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "수민은행",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 246,
            z: 164,
            image: "goverment.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "수민특별시청",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 20px Calibri,sans serif",
        },
        {
            x: 44,
            z: 7,
            image: "goverment.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "시작동주민센터",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 451,
            z: -8,
            image: "line1.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "시작역",
            textColor: "white",
            textStrokeColor: line1Color,
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 454,
            z: 79,
            image: "line2.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "시작역",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -92,
            z: -176,
            text: "약학관",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,
            offsetX: 0,
            offsetY: 0,
            font: "bold 12px Calibri,sans serif",
        },
        {
            x: -108,
            z: -100,
            text: "의학관",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,
            offsetX: 0,
            offsetY: 0,
            font: "bold 12px Calibri,sans serif",
        },
        {
            x: -27,
            z: -207,
            text: "이학관",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,
            offsetX: 0,
            offsetY: 0,
            font: "bold 12px Calibri,sans serif",
        },
        {
            x: -847,
            z: -380,
            image: "building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "은하은행",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 51,
            z: -206,
            image: "university.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "중앙도서관",
            textColor: universityColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -391,
            z: -496,
            image: "line2.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "중앙역",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 316,
            z: -78,
            image: "heritage.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "춘건루",
            textColor: heritageColor,
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -918,
            z: -376,
            image: "hotel.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "콘래드호텔",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: 47,
            z: -311,
            text: "학생회관",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 2,
            offsetX: 0,
            offsetY: 0,
            font: "bold 12px Calibri,sans serif",
        },
        {
            x: -249,
            z: -116,
            image: "building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "CN건설",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -455,
            z: -105,
            image: "building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "M&M로펌",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },
        {
            x: -665,
            z: -269,
            image: "building.pin.svg",
            imageAnchor: [0.5, 0.5],
            imageScale: 0.05,
            text: "SM텔레콤",
            textColor: "white",
            textStrokeColor: "black",
            textStrokeWidth: 3,
            offsetX: 0,
            offsetY: 20,
            font: "bold 15px Calibri,sans serif",
        },



        // do not delete the following two closing brackets
    ]
}
